// <auto-generated />
using System;
using Lession5NETCORE.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lession5NETCORE.Migrations
{
    [DbContext(typeof(Tes1Context))]
    partial class Tes1ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Lession5NETCORE.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("NAME");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NOTE");

                    b.HasKey("Id")
                        .HasName("PK__CATEGORY__3214EC272362531C");

                    b.ToTable("CATEGORY", (string)null);
                });

            modelBuilder.Entity("Lession5NETCORE.Models.Oder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ADDRESS");

                    b.Property<string>("Code")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("CODE");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("NAME");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("PHONE");

                    b.Property<double?>("TotalPrice")
                        .HasColumnType("float")
                        .HasColumnName("TOTAL_PRICE");

                    b.HasKey("Id")
                        .HasName("PK__ODERS__3214EC271743E051");

                    b.ToTable("ODERS", (string)null);
                });

            modelBuilder.Entity("Lession5NETCORE.Models.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("OdersId")
                        .HasColumnType("int")
                        .HasColumnName("ODERS_ID");

                    b.Property<double?>("Price")
                        .HasColumnType("float")
                        .HasColumnName("PRICE");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("PRODUCT_ID");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("QUANTITY");

                    b.Property<double?>("TotalPrice")
                        .HasColumnType("float")
                        .HasColumnName("TOTAL_PRICE");

                    b.HasKey("Id")
                        .HasName("PK__ORDER_DE__3214EC278A761570");

                    b.HasIndex("OdersId");

                    b.HasIndex("ProductId");

                    b.ToTable("ORDER_DETAIL", (string)null);
                });

            modelBuilder.Entity("Lession5NETCORE.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("CATEGORY_ID");

                    b.Property<string>("Images")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("IMAGES");

                    b.Property<string>("Name")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("NAME");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NOTE");

                    b.Property<double?>("Price")
                        .HasColumnType("float")
                        .HasColumnName("PRICE");

                    b.HasKey("Id")
                        .HasName("PK__PRODUCT__3214EC27FD32EFEF");

                    b.HasIndex("CategoryId");

                    b.ToTable("PRODUCT", (string)null);
                });

            modelBuilder.Entity("Lession5NETCORE.Models.OrderDetail", b =>
                {
                    b.HasOne("Lession5NETCORE.Models.Oder", "Oders")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OdersId")
                        .HasConstraintName("FK__ORDER_DET__ODERS__3E52440B");

                    b.HasOne("Lession5NETCORE.Models.Product", "Product")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("FK__ORDER_DET__PRODU__3F466844");

                    b.Navigation("Oders");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Lession5NETCORE.Models.Product", b =>
                {
                    b.HasOne("Lession5NETCORE.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("FK__PRODUCT__CATEGOR__398D8EEE");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Lession5NETCORE.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Lession5NETCORE.Models.Oder", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("Lession5NETCORE.Models.Product", b =>
                {
                    b.Navigation("OrderDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
